"""initial_migration

Revision ID: 867115b0f71f
Revises: 
Create Date: 2026-07-28 22:55:42.653231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '867115b0f71f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_student',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False, comment='Profile display name'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment="Profile origin: 'pdf' (uploaded CV) or 'form' (manual input)"),
    sa.Column('file_name', sa.String(length=512), nullable=True, comment="Original filename when source_type='pdf'"),
    sa.Column('s3_file_key', sa.String(length=512), nullable=True, comment='S3 object key for the uploaded PDF'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Processing status: pending, incomplete, or complete'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft-delete timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft-delete timestamp'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile_student.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile_student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_student_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False, comment="Attribute category (e.g. 'personal_info', 'education')"),
    sa.Column('key', sa.String(length=255), nullable=False, comment="Field name (e.g. 'full_name', 'years_of_experience')"),
    sa.Column('value', sa.Text(), nullable=True, comment='Field value in plain text format'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft-delete timestamp'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile_student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft-delete timestamp'),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistant_messages')
    op.drop_table('profile_student_attributes')
    op.drop_table('assistant_conversations')
    op.drop_table('profile_student')
    # ### end Alembic commands ###
