from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.profile_student_attribute.schema import ProfileStudentAttributeCreate


class ExtractorOutput(BaseModel):
    extracted: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Nested dict of raw extracted values by category",
    )


class MappingLogEntry(BaseModel):
    field_path: str = Field(..., description="Dot-notation path of the field")
    original: str = Field(..., description="Raw value before mapping")
    normalized: Any = Field(..., description="Value after mapping")
    reason: Optional[str] = Field(
        default=None, description="Why the mapping was applied"
    )


class MapperOutput(BaseModel):
    normalized: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Nested dict of normalised values by category",
    )
    mapping_log: List[MappingLogEntry] = Field(
        default_factory=list,
        description="Record of every transformation applied",
    )


class FieldContentError(BaseModel):
    error: str = Field(..., description="Human-readable error message")
    example_valid: Optional[str] = Field(
        default=None, description="Valid example to show the user"
    )
    example_invalid: Optional[str] = Field(
        default=None, description="Invalid example the user should avoid"
    )


class ValidationResult(BaseModel):
    missing: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Missing required keys per category",
    )
    content_errors: Dict[str, Any] = Field(
        default_factory=dict,
        description="Content errors per category",
    )

    @property
    def is_valid(self) -> bool:
        return not self.missing and not self.content_errors


class PipelineState(BaseModel):
    conversation_history: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Full message history: [{'role': 'user'|'assistant', 'content': str}]",
    )

    extracted_raw: ExtractorOutput = Field(
        default_factory=ExtractorOutput,
        description="Output of the Extractor node",
    )
    extracted_normalized: MapperOutput = Field(
        default_factory=MapperOutput,
        description="Output of the Mapper node",
    )
    validation: ValidationResult = Field(
        default_factory=ValidationResult,
        description="Output of the Validator node",
    )

    current_category: str = Field(
        default="personal_info",
        description="Category currently being collected",
    )
    next_field_to_ask: Optional[str] = Field(
        default=None,
        description="Specific missing field the assistant should ask for next",
    )
    category_complete: bool = Field(
        default=False,
        description="Whether the current_category has all required fields",
    )
    profile_complete: bool = Field(
        default=False,
        description="Whether every critical field across all categories is filled",
    )

    collected_attributes: List[ProfileStudentAttributeCreate] = Field(
        default_factory=list,
        description="Full merged attribute set for pipeline navigation and Writer context",
    )
    attributes_to_persist: List[ProfileStudentAttributeCreate] = Field(
        default_factory=list,
        description="New or changed attributes to upsert into the database this turn",
    )

    should_close: bool = Field(
        default=False,
        description="Writer set this to True when the user explicitly confirmed and the conversation should be closed",
    )

    assistant_response: Optional[str] = Field(
        default=None,
        description="Human-friendly message generated by the Writer",
    )
    raw_llm_response: Optional[str] = Field(
        default=None,
        description="Raw LLM output (for debugging / tracing)",
    )


class WriterInput(BaseModel):
    conversation_history: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Full conversation history for tone/context continuity",
    )
    current_category: str = Field(
        ..., description="Category the user is currently working on"
    )
    collected_summary: str = Field(
        default="",
        description="Human-readable summary of already-collected fields",
    )
    missing_fields: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Missing keys per category",
    )
    content_errors: Dict[str, Any] = Field(
        default_factory=dict,
        description="Content validation errors with examples",
    )
    next_field_to_ask: Optional[str] = Field(
        default=None,
        description="The single field the assistant should ask for now",
    )
    profile_complete: bool = Field(
        default=False,
        description="If True, Writer should present a confirmation summary",
    )
